version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Flutter/Dart
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Firebase Cloud Functions
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
